### ISSUE TITLE
Twitch links not getting detected

### ISSUE THREAD

**Issue by GMPranav** [GMPranav/SRCDVD#3]
Again, I ran it for pop1, it detected all the 5 runs with deleted YouTube VODs correctly, but the one run with unavailable twitch VOD was not detected. It also seems like twitch checks are not done in batches? I think it implementing it will improve performance even more as it allows a limit of 100

**Comment by partoftheworlD** [comment]
Should be fixed now 483a59b178b1b9fba92c452b1af9758ac8ce1970
