### ISSUE TITLE
Tool throwing ValueError

### ISSUE THREAD

**Issue by HexTree** [GMPranav/SRCDVD#5]
I used this back when it was released. Have tried to use it again today, with the same credentials as before, and am getting the following traceback:

> Enter the game's abbreviation in speedrun.com (eg. "smb1" for Super Mario Bros.): smb1
> Traceback (most recent call last):
>   File "main.py", line 15, in <module>
>   File "Data.py", line 30, in getRuns
> ValueError: invalid literal for int() with base 10: 'Number of runs</div><div class="bs-col-sm-6 row-list-text">7485'
> [10592] Failed to execute script 'main' due to unhandled exception!

Looks like something might have changed in the site formatting to cause it to crash.

**Comment by partoftheworlD** [comment]
Thanks for the report. Speedrun.com has changed CSS style names, hope this fixes the issue

**Comment by HexTree** [comment]
Worked for me, thanks.
